spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5555/car-store
    password: password
    username: user
    driver-class-name: org.postgresql.Driver
server:
  port: 9090
